services:
  ahoum:
    build: 
      context: .
    volumes:
      - ../:/ahoum
    links:
      - ahoum_mysql
    depends_on:
      - ahoum_mysql
    ports:
      - 8002:8000
    container_name: ahoum
    command: /bin/sh -c "while sleep 1000; do :; done"

  ahoum_mysql:
    image: mysql:8
    container_name: ahoum_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ahoum123
      MYSQL_DATABASE: booking_system
      MYSQL_USER: ahoum
      MYSQL_PASSWORD: ahoum123
    volumes:
      - ../db/:/var/lib/mysql
    ports:
      - 3306:3306
    

  ahoum_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ahoum_phpmyadmin
    restart: always
    depends_on:
      - ahoum_mysql
    environment:
      PMA_HOST: ahoum_mysql
      PMA_PORT: 3306
      PMA_USER: ahoum
      PMA_PASSWORD: ahoum123
    ports:
      - 100:80
    links:
      - ahoum_mysql
